### ISSUE TITLE
Drop `hide-readme-header` feature

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4157]
GitHub is shipping new features like crazy! The latest feature is [**table of contents for README**](https://twitter.com/natfriedman/status/1375430850620256257).

Well, not quite polished yet...

![image](https://user-images.githubusercontent.com/44045911/112585913-b7068200-8e35-11eb-96fa-b6283de6423b.png)

---

While `hide-readme-header` doesn't interfere with this feature, I see some reasons to drop it:

- Doesn't look nice (*We avoid orphans*)
  
  <table>
	<tr>
		<td>Currect
		<td>Default
	<tr>
		<td><img src="https://user-images.githubusercontent.com/44045911/112662483-b5b77280-8e92-11eb-87b8-e36f249d395f.png">
		<td><img src="https://user-images.githubusercontent.com/44045911/112662532-c23bcb00-8e92-11eb-9f22-8a1c2c681c9a.png">
  </table>

- Doesn't save any space

This is just to raise concern though, I don't think any action should be taken right now. Some other thoughts:

- ~~If it only works on repo home and for README only, can we extend it to support all Markdown files as well?~~ It's true 🎉

**Comment by fregante** [comment]
That feature is great! Makes me wonder if we should drop `collapse-markdown-sections` instead.

**Comment by kidonng** [comment]
I thought about it as well, but `collapse-markdown-sections` serves more purposes than a regular table of contents. For example you can take a screenshot with some sections folded to put the content you want in a single screen.

**Comment by j-f1** [comment]
Maybe pull the button out to the left of the readme?

<img width="400" alt="Screenshot_2021-03-26 13 27 24" src="https://user-images.githubusercontent.com/25517624/112670256-0f8a4f00-8e37-11eb-8c0a-d714cc898613.png"><img width="300" alt="Screenshot_2021-03-26 13 29 38" src="https://user-images.githubusercontent.com/25517624/112670489-55dfae00-8e37-11eb-9218-90aea51e9156.png">


Rough CSS:

```css
#readme > :first-child {
  height: 0;
  padding: 0 !important;
  border: none !important;
}
#readme > :first-child details {
  position: absolute;
  left: -4em;
  top: 1em;
}
```

**Comment by j-f1** [comment]
Alternatively, the space could be used to display the current header (or header breadcrumbs)

**Comment by fregante** [comment]
> For example you can take a screenshot with some sections folded to fit the content you want into a single screen.

Sounds niche and I’m not convinced 🤔

**Comment by fregante** [comment]
> Maybe pull the button out to the left of the readme

Doesn't seem worth the hassle and now the header is better than when the feature was introduced:

- 2 buttons
- white background
- fixed header

Maybe we could just reduce the padding to make it smaller, from `.p-3` to `.p-1` + some extra padding on the right side.

**Comment by kidonng** [comment]
Just noticed the header title now points to `#readme` (I don't remember whether it's there before the table of contents), serving as a quick way to go to the top of the README.

**Comment by kidonng** [comment]
Semi-related: I wonder why this issue still exists 🤔
![image](https://user-images.githubusercontent.com/44045911/115106714-e6be2b00-9f98-11eb-85ce-c25525a09978.png)

**Comment by fregante** [comment]
Likely due to `sticky-sidebar`

**Comment by kidonng** [comment]
The feature is expanded to all markup files. Sweet!
