### ISSUE TITLE
View File Broken in Firefox

### ISSUE THREAD

**Issue by brian-avery** [sindresorhus/refined-github#4178]
It seems that the view file link is broken on GitHub in Firefox. For instance:

* Go here: https://github.com/kubernetes/kubernetes/pull/100658/files
* Click on the 3 dots on the first file to open the menu.
* Click view file.

Instead of directing you to the file in the branch, it looks like it's skipping the branch in the URL (github.com/AlexeyPerevalov/kubernetes/blob//pkg/scheduler/testing/wrappers.go)

This results in a 404
![image](https://user-images.githubusercontent.com/8484260/113029308-45db0d80-915a-11eb-985e-b9372a174f17.png)

If I populate the branch in the URL: github.com/AlexeyPerevalov/kubernetes/blob/AddLimitsToReq/pkg/scheduler/testing/wrappers.go then it works.

If I disable refined-github, the link starts working

Looking in the console, I see: 

```
state is null global.js:344
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 74"  data: no] ExtensionCommon.jsm:74:12
TypeError: i.default.detectStore(...) is undefined h1-check.js:1:1301
GEThttps://github.com/AlexeyPerevalov/kubernetes/blob//pkg/scheduler/testing/wrappers.go
[HTTP/2 404 Not Found 226ms]

[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 74"  data: no] ExtensionCommon.jsm:74:12
TypeError: i.default.detectStore(...) is undefined h1-check.js:1:1301
XHRHEADhttps://github.com/AlexeyPerevalov/kubernetes/tree//pkg/scheduler/testing
[HTTP/2 404 Not Found 178ms]

XHRHEADhttps://github.com/AlexeyPerevalov/kubernetes/tree//pkg/scheduler
[HTTP/2 404 Not Found 171ms]

XHRHEADhttps://github.com/AlexeyPerevalov/kubernetes/tree//pkg
[HTTP/2 404 Not Found 258ms]

XHRHEADhttps://github.com/AlexeyPerevalov/kubernetes/tree/
[HTTP/2 404 Not Found 52ms]

XHRHEADhttps://github.com/AlexeyPerevalov/kubernetes/commits//pkg/scheduler/testing/wrappers.go
[HTTP/2 404 Not Found 263ms]

GEThttps://www.google.com/_/VerifiedReviewsGcrProxyUi/gen204/?tmambps=-1&rtembps=-1&rttms=-1
[HTTP/2 404 Not Found 18ms]

[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 74"  data: no]
```

**Comment by yakov116** [comment]
Duplicate of #4143

**Comment by brian-avery** [comment]
Thanks for looking at this so quickly. Just to clarify, I don't see any network errors other than the 404 for the missing branch and refreshing the page doesn't fix the issue.

**Comment by fregante** [comment]
If the URL should be 

```
https://github.com/kubernetes/kubernetes/blob/111a4c5f2f461bb1bd0e33ca0ba0afdbd57befdc/pkg/scheduler/testing/wrappers.go
```

but is

```
https://github.com/AlexeyPerevalov/kubernetes/blob//pkg/scheduler/testing/wrappers.go
```

then it's not exactly #4143

**Comment by tvalentyn** [comment]
Is there a workaround short of disabling the plugin?

**Comment by davidstosik** [comment]
To me it looks like this has been fixed already. Had the problem 10 hours ago, not anymore. 👌🏻

**Comment by tvalentyn** [comment]
Still broken for me in Chrome with RefinedGithub Version 21.3.26

**Comment by davidstosik** [comment]
Oh yeah, you are right! It seems to happen on some, but not all pull-requests for me... 🤔

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/4179
